`BASS_FX_VOLUME` support
ManagedBass/ManagedBass pull request #121
Opened 2023-06-23 15:01 UTC by KaleidonKep99

This pull request adds support for the [`BASS_FX_VOLUME`](https://www.un4seen.com/doc/#bass/BASS_FX_VOLUME_PARAM.html) effect, which is useful when the developer wants to change the volume of a decoding stream without having to use BASS_FX.

It required renaming the old Volume enum to VolumeBfx, which is a different effect offered by BASS_FX.

2024-04-04 14:46 UTC, smallketchup82 requested changes
Fix your access modifiers, since these classes can't be used otherwise.

Apart from that, these changes work for me (and I actually need them to make use of BassLoud's results)

2024-04-04 14:46 UTC, smallketchup82 commented on src/AddOns/BassFx/Effects/Objects/VolumeEffect.cs
> +    internal class Volume : Effect<VolumeParameters>
```suggestion
    public sealed class Volume : Effect<VolumeParameters>
```

2024-04-04 14:46 UTC, smallketchup82 commented on src/AddOns/BassFx/Effects/Structures/VolumeParameters.cs
> +    internal class VolumeParameters : IEffectParameter
```suggestion
    public class VolumeParameters : IEffectParameter
```

2024-04-05 14:25 UTC, merged

2024-04-07 21:48 UTC, smallketchup82 commented
@DustinBond I would like to quickly mention that you merged this PR without the proper access modifiers being applied. Both of the classes in this PR can't be used as they're marked as `internal` instead of `public`. It might be wise for either of us to fix this in a followup PR.

2024-04-08 22:18 UTC, DustinBond commented
@smallketchup82, would you mind sending me a new PR for this. I'm not actively working on this project, Probably a couple months until i'm back to it. Also If you get everything ready with Loudness, I'll be able to run complex detail test using loudness on Linux and Windows OS's. But have to wrap up a couple project before I can get back at this..

2024-04-09 13:56 UTC, smallketchup82 commented
Got it, will make a PR to address this